services:
    websc.view.custom_cache_headers_response_listener:
        class: AppBundle\EventListener\CustomCacheHeadersResponseListener
        arguments:
            - $content.view_cache$
            - '@ezpublish.api.service.content_type'
        tags:
            - { name: kernel.event_subscriber }

    websc.http_cache.http_cache_clear:
            class: AppBundle\HttpCache\HttpCacheClearService
            arguments:
                - "@fos_http_cache.cache_manager"
